<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['actualworkingdays'] = 'Jours de Travail Effectif';
$lang['earliestarrival'] = 'Arrivée le plus tôt';
$lang['extraworkeddays'] = '';
$lang['holidays'] = 'Fêtes';
$lang['latestdeparture'] = 'Dernière départ';
$lang['leaves'] = '';
$lang['missingdays'] = 'Jours Manquants';
$lang['perioddays'] = 'Période (Jours)';
$lang['requireddays'] = 'Jours Obligatoires';
$lang['weekends'] = 'Weekend';
?>