<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$settings['declineleavenotificationsubject'] = "Votre {1} demande a été refusée";

?>