<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['modifynotification_body'] = '';
$lang['modifynotification_subject'] = '';
?>