<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['abbreviation'] = 'Abréviation ';
$lang['addentity'] = 'Ajouter une entité';
$lang['addnewrepresentative'] = 'Ajouter un nouveau représentant';
$lang['address'] = 'Adresse';
$lang['affiliate'] = 'Filiale';
$lang['affjoinentity'] = 'Joindre l\'une de vos filiale à cette entité déjà existante';
$lang['alreadyjoined'] = 'La filiale sélectionnée a été déjà associée à cette entité';
$lang['alsocreatecurrentreports'] = 'Créer aussi les rapports trimestriels actuels correspondents';
$lang['both'] = 'Both';
$lang['buildingname'] = 'Nom de l\'Immeuble';
$lang['city'] = 'Ville';
$lang['companyname'] = 'Nom de l\'entreprise';
$lang['companynameabbr_title'] = 'Utiliser <em>Abbr.</em> pour abréviation.';
$lang['companyname_title'] = 'Fournir un nom commercial complet comme celui de l\'entreprise.';
$lang['companyshortname'] = 'Company Short Name';
$lang['competitorsupplier'] = 'Competitor Supplier';
$lang['country'] = 'Pays';
$lang['customer'] = 'Client';
$lang['email'] = 'Email';
$lang['entityalreadyexists'] = 'Une entité ayant le même nom existe déjà';
$lang['entitycreated'] = 'L\'Entité a été créée avec succès';
$lang['entitymightexist'] = 'Vous pourriez être entrain d\'ajouter une entité déjà existante:<br />
{1} Prière de contacter l\'administrateur si au moins une des données correspond à ceux mentionnées ci-dessous.';
$lang['entitytype'] = 'Type d\'entité';
$lang['errorcreatingentity'] = 'Erreur de création de l\'entité';
$lang['errorcreatingreprentative'] = 'Erreur de création du représentant';
$lang['errorwhilejoin'] = 'Une erreur s\'est produite lors de l\'inscription';
$lang['fax'] = 'Fax';
$lang['geolocation'] = 'Localisation Géographique';
$lang['invalidentityemail'] = 'Un e-mail d\'entité invalide a été fourni';
$lang['join'] = 'S\'inscrire';
$lang['joinedsuccessfully'] = 'Inscription réussie';
$lang['listavailablecustomers'] = 'Liste des clients disponibles';
$lang['listavailablesuppliers'] = 'Liste des fournisseurs disponibles';
$lang['local'] = 'Local';
$lang['longlattidue'] = 'Latitude Longitude [space in between]';
$lang['multinational'] = 'Multinational';
$lang['parentcompany'] = 'Parent Company';
$lang['pobox'] = 'Boîte Postale';
$lang['postcode'] = 'Code Postal';
$lang['potentialcustomer'] = 'Potential Customer';
$lang['presence'] = 'Presence';
$lang['producer'] = 'Producer';
$lang['regional'] = 'Regional';
$lang['repname_title'] = 'Nom et Prénom sans titre (ex. sans Mr., Ms etc...)';
$lang['representativecreated'] = 'Le Représentant a été créé avec succès';
$lang['representativeexists'] = 'Un représentant du même nom existe déjà';
$lang['representativename'] = 'Nom du représentant';
$lang['representatives'] = 'Représentants';
$lang['segments'] = 'Secteurs';
$lang['specifyanaffiliate'] = 'Veuillez indiquer une filiale';
$lang['specifyasegment'] = 'Veuillez specifier un secteur d\'activité';
$lang['specifycompanyname'] = 'Veuillez indiquer un nom d\'entreprise';
$lang['specifyrepemail'] = 'Précisez l\'email du représentant ';
$lang['specifyrepresentative'] = 'Précisez au moins un représentant';
$lang['supplier'] = 'Fournisseur';
$lang['telephone'] = 'Numéro de téléphone';
$lang['trader'] = 'Trader';
$lang['website'] = 'Site Web';
?>