<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['dateformat'] = 'Format de la Date';
$lang['fieldrepeated'] = '';
$lang['foreignsystem'] = 'Système étranger';
$lang['importoptions'] = 'Options';
$lang['importsales'] = 'Ventes Importation';
$lang['importsalesallowedtypes'] = 'Seuls les fichiers CSV sont autorisés';
$lang['previewsales'] = 'Afficher les Ventes';
$lang['resolvecustomername'] = 'Résoudre Nom du Client';
$lang['resolveproductname'] = 'Résoudre Nom du Produit';
$lang['resolvesuppliername'] = 'Résoudre Nom du Fournisseur';
$lang['selectattfile'] = 'Sélectionnez un fichier';
?>