<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['addrepresentative_note'] = '';
$lang['monday'] = 'Lundi';
$lang['telephone'] = 'Téléphone';
?>