<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['addrepresentative_note'] = 'Les représentants sont les personnes avec lesquels vous traitez dans l’entreprise  et non pas vous.<br />
<br />
Indiquez toujours le nom complet, sans titre.';
$lang['monday'] = 'Lundi';
$lang['telephone'] = 'Téléphone';
?>