<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['upcomingholidays_message'] = '';
$lang['upcomingholidays_subject'] = '';
?>