<?php

/* * *******************************\ 
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['adminreadyassist'] = 'Les administrateurs sont prêts à vous aider.';
$lang['callonnum'] = 'Appelez au {1}';
$lang['contactbyemail'] = 'Contactez-les par e-mail';
$lang['currqreportingstats'] = 'Current rapports trimestriels stats';
$lang['duereports'] = 'Rapports trimestriels dû';
$lang['edityourprofile'] = 'Modifiez votre profil';
$lang['fillvreport'] = 'Remplir un rapport de visite';
$lang['generateqreports'] = 'Produire des rapports trimestriels';
$lang['intotal'] = 'au total';
$lang['lastfinalized'] = 'Derniers rapports finalisés';
$lang['listqreports'] = 'Liste des rapports trimestriels';
Vous êtes en mesure de préparer vos rapports mensuels et trimestriels, faire une demande de congé et plus.';
$lang['systemnews'] = 'Magister nouvelles';
$lang['timecity'] = ' {
    1
} {
    2
} temps';
$lang['timecity2'] = ' {
    1
} {
    2
} temps';
$lang['timegmt'] = ' {
    1
} UTC temps';
$lang['unfinalized'] = 'non finalisé';
$lang['usefulshortcuts'] = 'Userful shortcuts';
$lang['weheretohelp'] = 'Nous sommes là pour vous aider';
$lang['worldtime'] = 'Temps du monde';
?>