<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['passwordalreadyused'] = '';
$lang['passwordhasexpired'] = '';
$lang['passwordpattern_tooltip'] = '';
$lang['pwdpatternnomatch'] = '';
?>