<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['accesssurveylink'] = '';
$lang['basictemplateinfo'] = '';
$lang['surveyquestions'] = '';
?>