<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$settings['present2'] = "Prente2";
$settings['test2'] = "jusment2";
$settings['test2'] = "jusment2";

?>