<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$settings['present3'] = "Prente2";
$settings['test3'] = "jusment23";

?>