<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['alreadyexists'] = "Un fichier portant le m?me nom existe d?j";
$lang['erroruploading'] = "Une erreur s'est produite lors du t?l?chargement.";
$lang['iwas'] = "j'étais";
$lang['sizetoobig'] = "La taille du fichier est trop grande.";
$lang['typenotallowed'] = "Le type de fichier que vous essayez de t?l?charger n'est pas autoris";
$lang['uploaded'] = "Le fichier a ?t? t?l?charg";

?>