<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['addsuppliernotification_message'] = 'Hello,
<br />
<strong>{1}</strong> has been created on the system.
Click <a href="{2}">here</a> to view their profile.

Regards';
$lang['addsuppliernotification_subject'] = 'A new supplier has been added';
?>