<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the CMS Module
  \******************************** */

$settings['adminemail'] = "server.admin@orkila.com";
$settings['dateformat'] = "M d, Y";
$settings['enablecompression'] = "0";
$settings['exportdirectory'] = "exports/";
$settings['ftpanonymous'] = "1";
$settings['ftppassword'] = "T0ny@ssad";
$settings['ftpserver'] = "127.0.0.1";
$settings['ftpusername'] = "administrator";
$settings['gziplevel'] = "4";
$settings['itemsperlist'] = "10";
$settings['maintenancemessage'] = "The system in undergoing maintenance.";
$settings['metadesc'] = "test";
$settings['metakeywords'] = "";
$settings['newsattachmentspath'] = "uploads/newsattachments";
$settings['newsimagespath'] = "uploads/newsimages";
$settings['onmaintenance'] = "0";
$settings['pageimagespath'] = "uploads/pagesimages/";
$settings['robots'] = "Index, Follow";
$settings['sitename'] = "Orkila";
$settings['slogan'] = "companyslogan";
$settings['timeformat'] = "h:i A";
$settings['usefriendlyurls'] = "1";
$settings['websiteaudits'] = "";
?>