<?php

/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$settings['adminemail'] = "hussein.barakat@edu.esiee.fr";
$settings['bugnotificationcontacts'] = "hussein.barakat@edu.esiee.fr";
$settings['clearlogperiod'] = "30";
$settings['dateformat'] = "M d, Y";
$settings['enablecompression'] = "1";
$settings['exportdirectory'] = "exports/";
//$settings['failedlogintime'] = "10";
$settings['gziplevel'] = "4";
$settings['idletime'] = "8640000";
$settings['itemsperlist'] = "1000";
//$settings['loginattempts'] = "5";
$settings['maintenancemessage'] = "The system is undergoing maintenance. Thank you for your patience";
$settings['onmaintenance'] = "0";
$settings['passwordArchiveRetention'] = "10";
$settings['profilepicdir'] = "images/profilepictures/";
$settings['q1end'] = "03-31";
$settings['q1start'] = "01-01";
$settings['q2end'] = "06-30";
$settings['q2start'] = "04-01";
$settings['q3end'] = "09-30";
$settings['q3start'] = "07-01";
$settings['q4end'] = "12-31";
$settings['q4start'] = "10-01";
$settings['qraddrecipients'] = "";
$settings['reportdeadline'] = "15";
$settings['sendreportsonapprove'] = "0";
$settings['systemtitle'] = "Magister";
$settings['timeformat'] = "h:i A";
$settings['weeklyplan_deletehours'] = "2880";
$settings['weeklyplan_editdays'] = "30";
$settings['deadlinescolor'] = "#F30021";
$settings['eventscolor'] = "#068BBE";
$settings['lecturescolor'] = "#49B41B";
$settings['recommendationscolor'] = "#FF7400";
$settings['lecturelength'] = "10800";
?>