<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$settings['adminemail'] = "zaher.reda@orkila.com";
$settings['dateformat'] = "M d, Y";
$settings['enablecompression'] = "0";
$settings['entitylogodir'] = "uploads/entitieslogos/";
$settings['exportdirectory'] = "exports/";
$settings['failedlogintime'] = "2";
$settings['fxfeedurl'] = "http://www.webservicex.net/CurrencyConvertor.asmx/ConversionRate?FromCurrency={FROM}&ToCurrency={TO}";
$settings['gziplevel'] = "8";
$settings['idletime'] = "240";
$settings['itemsperlist'] = "10";
$settings['loginattempts'] = "6";
$settings['maintenancemessage'] = "The system in undergoing maintenance. ";
$settings['onmaintenance'] = "0";
$settings['profilepicdir'] = "images/profilepictures/";
$settings['q1end'] = "31/03";
$settings['q1start'] = "01/01";
$settings['q2end'] = "30/06";
$settings['q2start'] = "01/04";
$settings['q3end'] = "30/09";
$settings['q3start'] = "01/07";
$settings['q4end'] = "31/12";
$settings['q4start'] = "01/10";
$settings['reportdeadline'] = "15";
$settings['saletypes'] = "distribution;indent;both";
$settings['sendreportsonapprove'] = "0";
$settings['sendreportsto'] = "zaher.reda@orkila.com";
$settings['systemtitle'] = "OCOS";
$settings['timeformat'] = "h:i A";

?>