<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['adddaysapprovedmessage'] = 'Dear {1},<br />
<br />
Your request for {2} days was approved.<br />
<br />
Regards';
$lang['adddaysnotificationsubject'] = '{1} requested additional holiday days [{2}]';
$lang['adddaysrequestapproval'] = '{1} requested the following additional holiday days:<br />
<br />
Number of days: {2}<br />
<br />
Corresponding date: {3}<br />
<br />
Justification: {4}<br />
<br />
{4}';
$lang['additionadaysapprovedsubject'] = 'Your request for additional days has been approved';
$lang['autorespondermessage'] = 'I am not available from {1} to {2}.';
$lang['autorespondermessagecontact'] = 'Please contact {1} ({2}) for urgent issues.';
$lang['autorespondermessagelimitedemail'] = 'I have limited access to emails.';
$lang['businesstravel'] = 'Business Travel';
$lang['declineleavenotificationmessage'] = 'Dear {1},<br />
<br />
Your {2} between {3} and {4} was declined.<br />
<br />
Regards';
$lang['declineleavenotificationsubject'] = 'Your {1} request was declined';
$lang['leaveapprovedmessage'] = 'Dear {1},<br />
<br />
Your {2} between {3} and {4} was approved.<br />
<br />
Regards';
$lang['leaveapprovedsubject'] = 'Your leave request was approved';
$lang['leavenotificationmessage'] = '{1} {6} {2} between <strong>{3}</strong> and <strong>{4}</strong>{5}<br />
{7}{8}';
$lang['leavenotificationmessage_contactperson'] = 'You may contact {1} in case of urgent issues on {2}.';
$lang['leavenotificationmessage_days'] = ' - {1} working day(s).';
$lang['leavenotificationmessage_owncontact_email'] = '{1} will have access to e-mail, but can also be reached on: {2}';
$lang['leavenotificationmessage_owncontact_limitedemail'] = 'While away, {1} will have limited access to e-mail, but can be reached on: {2}';
$lang['leavenotificationsubject'] = '{1} {3} {2} ({4}{5})';
$lang['leavenotificationsubject_isat'] = 'is in/at';
$lang['leavenotificationsubject_taking'] = 'is taking a';
$lang['leavenotificationsubject_took'] = 'took a';
$lang['leavenotificationsubject_wasat'] = 'was in/at';
$lang['leavenotificationsubject_willbeat'] = 'will be in/at';
$lang['modifyleavemessage'] = '{1} modified their leave as follows:<br />
Type: {2}<br />
Start date: {3}<br />
End date: {4} {5} <br />
Reason: {6}<br />
{7}<br />
<br />
To approve simply reply to the request message, or click <a href=\'{8}\'>here</a> to approve or discuss it.';
$lang['modifyleavemessage_stats'] = '<strong>Leaves Stats:</strong><br />
<br />
Current final balance is <strong>{1}</strong> days. It will become <strong>{2}</strong> after approving this leave.';
$lang['modifyleavenotificationmessage'] = '{1} {2} {3} between <strong>{4}</strong> and <strong>{5}</strong>{6}<br />
{7}';
$lang['modifyleavenotificationsubject'] = '{1} modified their leave {2}';
$lang['newleavemsgsubject'] = 'New message about leave request';
$lang['reinitializebalances'] = 'Reinitialize Balances';
$lang['requestleavemessage'] = '{1} requested a leave as follows:<br />
Type: {2}<br />
Start date: {3}<br />
End date: {4} {5} <br />
Reason: {6}<br />
{7}<br />
<br />
To approve simply reply to this message, or click <a href=\'{8}\'>here</a> to approve it or discuss it.';
$lang['requestleavemessagesupervisor'] = '{1} requested a leave as follows:<br />
Type: {2}<br />
Start date: {3}<br />
End date: {4}<br />
Reason: {5}<br />
Approved by: {6}<br />
<br />
To approve simply reply to the request message, or click <a href=\'{7}\'>here</a> to approve or discuss it.
<br />';
$lang['requestleavemessage_stats'] = '<strong>Leaves Stats:</strong><br />
<br />
Current final balance is <strong>{1}</strong> days. It will become <strong>{2}</strong> after approving this leave. ';
$lang['requestleavesubject'] = '{1} requested a {2} [{3}]';
$lang['revokeleavenotificationmessage'] = '{1} revoked the {2}{3} between <strong>{4}</strong> and <strong>{5}</strong>.';
$lang['revokeleavenotificationmessageuser'] = 'Dear {1},<br />
<br />
Your {2}{3} between {4} and {5} was revoked.<br />
<br />
Regards';
$lang['revokeleavenotificationsubject'] = '{1} revoked their {2}{3}';
$lang['revokeleavenotificationsubjectuser'] = 'Your {1}{2} was revoked';
$lang['tmplanfinancenotification'] = '{1} planned a trip with the following expenses';
$lang['ocosquestion'] = 'OCOS Question';
$lang['apporvinganonexistingleavesubject'] = 'You just approved a non existing leave';
$lang['apporvinganonexistingleave'] = 'Dear {1},<br />
<br />
You Just tried to approve a deleted or revoked leave.
<br />
Regards';
$lang['currentbalance'] = 'Current Balance';
?>