<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['modifynotification_body'] = 'The page {1} has been modified as follows:

Title {2} similar: {3}
Summary {4} similar: {5}
Body {6} similar: {7} ';
$lang['modifynotification_subject'] = 'Modified News: {1}';
?>