<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['abbreviation'] = 'Abbr.';
$lang['addentity'] = 'Add an Entity';
$lang['addnewrepresentative'] = 'Add New Representative';
$lang['address'] = 'Address';
$lang['affiliate'] = 'Affiliate';
$lang['affjoinentity'] = 'Join one of your affiliates to this existing entity';
$lang['alreadyjoined'] = 'The selected affiliate has already joined this entity';
$lang['alsocreatecurrentreports'] = 'Also create corresponding current quarter\'s reports';
$lang['both'] = 'Both';
$lang['buildingname'] = 'Building name';
$lang['city'] = 'City';
$lang['companyname'] = 'Company name';
$lang['companynameabbr_title'] = 'Use <em>Abbr.</em> for abbreviation or short name.';
$lang['companyname_title'] = 'Provide complete commercial name as the company name.';
$lang['companyshortname'] = 'Company Short Name';
$lang['companysize'] = 'Company Size';
$lang['competitorsupplier'] = 'Competitor Supplier';
$lang['country'] = 'Country';
$lang['customer'] = 'Customer';
$lang['email'] = 'Email';
$lang['entityalreadyexists'] = 'An entity with the same name already exists';
$lang['entitycreated'] = 'Entity was successfully created';
$lang['entitymightexist'] = 'You might be adding an already existing entity: {1}If any of the above match, please contact the administrator.';
$lang['entitymightexistwarning'] = 'You might be adding an already existing entity. Please Check the below entities.';
$lang['entitytype'] = 'Entity type';
$lang['errorcreatingentity'] = 'Error creating entity';
$lang['errorcreatingreprentative'] = 'Error creating representative';
$lang['errorwhilejoin'] = 'An error occured while joining';
$lang['fax'] = 'Fax';
$lang['geolocation'] = 'Geographic Location';
$lang['invalidentityemail'] = 'An invalid entity email was provided';
$lang['issuportivedescription'] = 'Specified if the person supports our business or not.<br />
In case of a customer, he/she might be supportive of a competitor supplier.<br />In case of a supplier, their representative might be supportive of another agent.';
$lang['issupportive'] = 'Is Supportive';
$lang['join'] = 'Join';
$lang['joinedsuccessfully'] = 'Joined Successfully';
$lang['listavailablecustomers'] = 'List of Available Customers';
$lang['listavailablesuppliers'] = 'List of Available Suppliers';
$lang['local'] = 'Local';
$lang['longlattidue'] = 'Longitude Latitude [space in between]';
$lang['multinational'] = 'Multinational';
$lang['parentcompany'] = 'Parent Company';
$lang['pobox'] = 'PO Box';
$lang['postcode'] = 'Post code';
$lang['potentialcustomer'] = 'Potential Customer';
$lang['presence'] = 'Presence';
$lang['producer'] = 'Producer';
$lang['regional'] = 'Regional';
$lang['repname_title'] = 'Full name without title (i.e. without Mr., Ms etc...)';
$lang['representativecreated'] = 'The representative was successfully created';
$lang['representativeexists'] = 'A representative with the same name already exists';
$lang['representativename'] = 'Representative name';
$lang['representatives'] = 'Representatives (Contact Persons)';
$lang['segments'] = 'Segments';
$lang['specifyanaffiliate'] = 'Please specify an affiliate';
$lang['specifyasegment'] = 'Please specify an business segment';
$lang['specifycompanyname'] = 'Please specify a company name';
$lang['specifyrepemail'] = 'Specify representative email';
$lang['specifyrepresentative'] = 'Specify at least one represenative';
$lang['supplier'] = 'Supplier';
$lang['telephone'] = 'Phone number';
$lang['trader'] = 'Trader';
$lang['website'] = 'Website';
$lang['joinentities'] = 'Assign yourself to the following entities';
$lang['alreadyassigned'] = 'represnts entities that are already assigned to you.';
$lang['entity'] = 'Entity';
$lang['type'] = 'Type';
$lang['userassignmentsubject'] = 'User Assignments';
$lang['userassignmentmessage'] = '{1} was assigned to {2}';
?>