<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['dateformat'] = 'Date Format';
$lang['fieldrepeated'] = 'Field was Selected Multiple Times';
$lang['foreignsystem'] = 'Foreign System';
$lang['importoptions'] = 'Options';
$lang['importsales'] = 'Import Sales';
$lang['importsalesallowedtypes'] = 'Only CSV files are allowed';
$lang['previewsales'] = 'Preview Sales';
$lang['resolvecustomername'] = 'Resolve Customer Name';
$lang['resolveproductname'] = 'Resolve Product Name';
$lang['resolvesuppliername'] = 'Resolve Supplier Name';
$lang['selectattfile'] = 'Select a File';
?>