<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['amountabbr'] = 'Amt';
$lang['amounts'] = 'Amounts US';
$lang['any'] = 'Any';
$lang['busmanagerabbr'] = 'BM';
$lang['cost'] = 'Cost';
$lang['dayabbr'] = 'D';
$lang['detailed'] = 'Detailed';
$lang['filters'] = 'Filters';
$lang['fromdate'] = 'From';
$lang['generatereport'] = 'Generate Report';
$lang['generatesalesreport'] = 'Generate Sales Report';
$lang['gmargin'] = 'G. Margin';
$lang['grossmargin'] = 'Gross Margin';
$lang['monthtotal'] = 'Month Total';
$lang['name'] = 'Name';
$lang['netmargin'] = 'Net Margin';
$lang['nmargin'] = 'N. Margin';
$lang['numorders'] = '# Orders';
$lang['price'] = 'Price';
$lang['products'] = 'Products';
$lang['ptdays'] = 'PT Days';
$lang['quantityabbr'] = 'Qty';
$lang['reinvoice'] = 'Re-Invoicing';
$lang['saletype'] = 'Sale Type';
$lang['sector'] = 'Sector';
$lang['sellingprice'] = 'Selling Price';
$lang['stock'] = 'Stock';
$lang['todate'] = 'To';
$lang['topcustomers'] = 'Top Customers';
$lang['topemployees'] = 'Top Employees';
$lang['topproducts'] = 'Top Products';
$lang['topsuppliers'] = 'Top Suppliers';
$lang['total'] = 'Total';
$lang['totalcost'] = 'Total Cost';
$lang['type'] = 'Type';
$lang['uptototal'] = 'Up to Total';
$lang['weektotal'] = 'Week Total';
?>