<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['amountabbr'] = 'Amt';
$lang['amounts'] = 'Amounts US';
$lang['any'] = 'Any';
$lang['busmanagerabbr'] = 'BM';
$lang['cost'] = 'Cost';
$lang['costlocal'] = 'Cost (Local Curr)';
$lang['customerssummary'] = 'Customers Summary';
$lang['dayabbr'] = 'D';
$lang['detailed'] = 'Detailed';
$lang['filters'] = 'Filters';
$lang['fromdate'] = 'From';
$lang['fxtype'] = 'FX Rate Type';
$lang['generatereport'] = 'Generate Report';
$lang['generatesalesreport'] = 'Generate Sales Report';
$lang['gmargin'] = 'G. Margin';
$lang['grossmargin'] = 'Gross Margin';
$lang['lastmonthrate'] = 'Last Month';
$lang['linenetamt'] = 'Amount';
$lang['marginperc'] = 'Margin %';
$lang['grossmarginperc'] = '%';
$lang['monthaveragerate'] = 'Month Average';
$lang['monthtotal'] = 'Month Total';
$lang['name'] = 'Name';
$lang['netmargin'] = 'Net Margin';
$lang['nmargin'] = 'N. Margin';
$lang['numorders'] = '# Orders';
$lang['objective'] = 'Objective';
$lang['price'] = 'Price';
$lang['priceactual'] = 'Price';
$lang['products'] = 'Products';
$lang['ptdays'] = 'PT Days';
$lang['purchaseprice'] = 'Purchase Price';
$lang['qtyinvoiced'] = 'Qty';
$lang['quantityabbr'] = 'Qty';
$lang['realrate'] = 'Real Rate';
$lang['reinvoice'] = 'Re-Invoicing';
$lang['salesrepsummary'] = 'Sales Rep. Summary';
$lang['saletype'] = 'Sale Type';
$lang['sector'] = 'Sector';
$lang['segmentsummary'] = 'Segment Summary';
$lang['sellingprice'] = 'Selling Price';
$lang['sendbyemail'] = 'Send by Email';
$lang['stock'] = 'Stock';
$lang['suppliersummary'] = 'Suppliers Summary';
$lang['todate'] = 'To';
$lang['topcustomers'] = 'Top Customers';
$lang['topemployees'] = 'Top Employees';
$lang['topproducts'] = 'Top Products';
$lang['topsuppliers'] = 'Top Suppliers';
$lang['total'] = 'Total';
$lang['totalcost'] = 'Total Cost';
$lang['type'] = 'Type';
$lang['uptototal'] = 'Up to Total';
$lang['weektotal'] = 'Week Total';
$lang['yearaveragerate'] = 'Year Average';
$lang['yearlatestrate'] = 'Year\'s Latest';
$lang['salesrepresentative'] = 'Sales Representative';
$lang['warehouse'] = 'Warehouse';

$lang['generateclassificationcharts'] = 'Generate Classification Charts';
$lang['currentdata'] = 'Current Amount';
$lang['prevdata'] = 'Previous Amount';
$lang['position'] = 'Position';
$lang['topten'] = 'Top 10';
$lang['salerep'] = 'Salesman';
$lang['products'] = 'Products';
$lang['suppliers'] = 'Suppliers';
$lang['byytd'] = 'YTD';
$lang['bymonth'] = 'of the Month';
$lang['byquarter'] = 'of the quarter';
$lang['wholeperiod'] = 'of the Whole Period';
$lang['chart'] = 'Chart';
$lang['rank'] = 'Rank';
?>