<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['approvedby'] = 'Approved By';
$lang['bugslist'] = 'Bugs List';
$lang['children'] = 'Children';
$lang['completed'] = 'Completed';
$lang['createrechange'] = 'Create Requirement Change';
$lang['createrequirement'] = 'Create Requirement';
$lang['description'] = 'Description';
$lang['interface'] = 'Interface';
$lang['parent'] = 'Parent';
$lang['performance'] = 'Performance';
$lang['reference'] = 'Reference';
$lang['requestedby'] = 'Requested By';
$lang['requirementchange'] = 'Requirements Change';
$lang['requirementslist'] = 'Requirements List';
$lang['security'] = 'Security';
$lang['title'] = 'Title';
$lang['markascompleted'] = 'Mark as Completed'
?>