<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['category'] = 'Category';
$lang['changeview'] = 'Change View';
$lang['createfolder'] = 'Create Folder';
$lang['customizemessage'] = 'Customize message';
$lang['date'] = 'Date';
$lang['description'] = 'Description';
$lang['fileslist'] = 'Files List';
$lang['filesuccessfullyshared'] = 'File successfully shared';
$lang['filetitleexists'] = 'The title you have chosen is already in use';
$lang['folder'] = 'Folder';
$lang['message'] = 'Message';
$lang['parentfolder'] = 'Parent folder';
$lang['preventaccess'] = 'Prevent Access';
$lang['preventaccessnote'] = 'If not specified, the files inherit the parent\'s permissions.';
$lang['preventallnewusers'] = 'Prevent all new users';
$lang['preventreading'] = 'Prevent Reading';
$lang['preventwriting'] = 'Prevent Writing';
$lang['selectfile'] = 'Select a File';
$lang['share'] = 'Share';
$lang['shareafile'] = 'Share a File';
$lang['sharebymail'] = 'Share by Email';
$lang['sharedfileslist'] = 'List Of Shared Files';
$lang['size'] = 'Size';
$lang['subject'] = 'Subject';
$lang['suredeletefile'] = 'Are you sure you want to delete';
$lang['title'] = 'Title';
$lang['type'] = 'Type';
$lang['unknowntype'] = 'Unknown type';
$lang['youaretoshare'] = 'You are about to share';
$lang['uploadfile'] = "Share a File";
$lang['deletefile'] = 'Delete File';
$lang['edit'] = 'Edit File';
$lang['viewfileversions'] = 'View Versions';
$lang['sharebyemail'] = 'Share File';
?>