<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['accountemailnotfound'] = 'No account corresponding to this email was found';
$lang['accountsuspended'] = 'Sorry, you can\'t access OCOS.';
$lang['add'] = 'Add';
$lang['addcustomers'] = 'Add Customers';
$lang['addproducts'] = 'Add Products';
$lang['addrepresentative_note'] = 'Representatives (contact persons) are not you, they are the persons you deal with from the entity side.<br />
<br />
Always provide complete name, without title.';
$lang['addsuppliers'] = 'Add Suppliers';
$lang['affiliate'] = 'Affiliate';
$lang['affiliateslist'] = 'Affiliates List';
$lang['april'] = 'April';
$lang['attendance'] = 'Attendance';
$lang['august'] = 'August';
$lang['calendar'] = 'Calendar';
$lang['cancel'] = 'Cancel';
$lang['contactadministrator'] = 'Contact Administrator';
$lang['contents'] = 'Contents';
$lang['copyright'] = 'Copyright © Orkila Holding';
$lang['createreports'] = 'Create Reports';
$lang['crm'] = 'CRM';
$lang['customer'] = 'Customer';
$lang['customerslist'] = 'Customers List';
$lang['december'] = 'December';
$lang['delimiter'] = 'Delimiter';
$lang['development'] = 'Development';
$lang['edityouraccount'] = 'Edit your Account';
$lang['email'] = 'Email';
$lang['emailsentcontainpassword'] = 'A message containing your new password was sent to your email';
$lang['emailtosendpassword'] = 'Enter your email to send your new password to';
$lang['employee'] = 'Employee';
$lang['error'] = 'Error';
$lang['errorsaving'] = 'An error occurred while saving';
$lang['errorsendingemail'] = 'An error occured while sending email';
$lang['february'] = 'February';
$lang['filesharing'] = 'File Sharing';
$lang['fillallrequiredfields'] = 'Please fill all required fields';
$lang['fillreport'] = 'Fill Report';
$lang['fillrequiredfields'] = 'Please make sure to fill all required fields';
$lang['filter'] = 'Filter';
$lang['firstvisit'] = 'This is your first visit';
$lang['forgotyourpassword'] = 'Forgot your Password?';
$lang['fromdate'] = 'From';
$lang['generatereport'] = 'Generate Report';
$lang['goback'] = 'Go back';
$lang['grouppurchase'] = 'Group Purchase';
$lang['home'] = 'Home';
$lang['humanresources'] = 'Human Resources';
$lang['invalidemailaddress'] = 'Invalid email address';
$lang['invalidlogin'] = 'Invalid login details';
$lang['january'] = 'January';
$lang['july'] = 'July';
$lang['june'] = 'June';
$lang['lastvisit'] = 'Your last visit was on {1} at {2}';
$lang['listreports'] = 'List Reports';
$lang['login'] = 'Login';
$lang['loginsuccess'] = 'Login successful';
$lang['logout'] = 'Logout';
$lang['march'] = 'March';
$lang['may'] = 'May';
$lang['meetings'] = 'Meetings';
$lang['monday'] = 'Monday';
$lang['monthly'] = 'Monthly';
$lang['na'] = 'N/A';
$lang['next'] = 'Next';
$lang['nextcaps'] = 'NEXT';
$lang['no'] = 'No';
$lang['nomatchfound'] = 'No match was found';
$lang['november'] = 'November';
$lang['october'] = 'October';
$lang['orkilaIS'] = 'OCOS';
$lang['password'] = 'Password';
$lang['perlist'] = 'Per list';
$lang['pleaselogin'] = 'Please Login';
$lang['portal'] = 'Portal';
$lang['prev'] = 'Prev';
$lang['prevcaps'] = 'PREV';
$lang['product'] = 'Product';
$lang['quarterly'] = 'Quarterly';
$lang['reachedmaxattempts'] = 'You have reached the max allowed failed login attempts,<br />
you may login after {1} minutes.';
$lang['readmore'] = 'Read more';
$lang['reporting'] = 'Reporting';
$lang['reputation'] = 'Reputation';
$lang['reset'] = 'Reset';
$lang['resetpassword'] = 'Reset Password';
$lang['row'] = 'Row';
$lang['savecaps'] = 'SAVE';
$lang['sectionnopermission'] = 'You don\'t have permissions to access this section';
$lang['september'] = 'September';
$lang['sessionexpired'] = 'Your sessions has expired, please login again.';
$lang['successfullysaved'] = 'Successfully saved';
$lang['supplier'] = 'Supplier';
$lang['supplierslist'] = 'Suppliers List';
$lang['surveys'] = 'Surveys';
$lang['telephone'] = 'Telephone';
$lang['todate'] = 'To';
$lang['travelmanager'] = 'Travel Manager';
$lang['username'] = 'Username';
$lang['welcomeuser'] = 'Welcome {1}!';
$lang['yes'] = 'Yes';
?>