<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['bm'] = 'Business Manager';
$lang['comments'] = 'Comments';
$lang['createforecast'] = 'Create Quantities Forecast';
$lang['generateforecast'] = 'Generate Quantities Forecast';
$lang['globalprice'] = 'Global Price';
$lang['grouppurchasetabular'] = 'Tabular View';
$lang['incoterm'] = 'Incoterm';
$lang['informconcernedparties'] = 'Inform Concerned Parties';
$lang['price'] = 'Price';
$lang['priceperaffiliate'] = 'Price per Affiliate';
$lang['priceproduct'] = 'Price Product';
$lang['pricing'] = 'Price Product';
$lang['quantitiesforecast'] = 'Quantities Forecast';
$lang['remarks'] = 'Remarks';
$lang['saletype'] = 'Sale type';
$lang['total'] = 'Total';
$lang['unit'] = 'Unit';
$lang['validthrough'] = 'Valid through';
$lang['onbehalf'] = 'On Behalf Of';
$lang['checkforecast'] = 'The deadline to update your forecast is on the 10th of the Month.<br />
Affiliates:<br/>
{1}<br/>
Suppliers:<br/>
{2}<br/>
Years:<br/>
{3}<br/>
Kindly access OCOS the soonest possible and verify/update the data.';
$lang['check'] = 'Check';
$lang['update'] = 'Update';
$lang['gpreminder'] = 'Update Group Purchase Forcast Reminder';
$lang['priceslist'] = 'Prices List';
?>