<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['bm'] = 'Business Manager';
$lang['comments'] = 'Comments';
$lang['createforecast'] = 'Create Quantities Forecast';
$lang['generateforecast'] = 'Generate Quantities Forecast';
$lang['globalprice'] = 'Global Price';
$lang['grouppurchasetabular'] = 'Tabular View';
$lang['incoterm'] = 'Incoterm';
$lang['informconcernedparties'] = 'Inform Concerned Parties';
$lang['price'] = 'Price';
$lang['priceperaffiliate'] = 'Price per Affiliate';
$lang['priceproduct'] = 'Price Product';
$lang['quantitiesforecast'] = 'Quantities Forecast';
$lang['remarks'] = 'Remarks';
$lang['saletype'] = 'Sale type';
$lang['total'] = 'Total';
$lang['unit'] = 'Unit';
$lang['validthrough'] = 'Valid through';
?>