<?php
/* * *******************************\ 
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['calendar_taskreminder_message'] = 'Hello {1},<br />
<br />
{2}';
$lang['calendar_taskreminder_subject'] = 'Tasks Reminder';
$lang['declineleavenotificationmessage'] = 'Dear {1},<br />
<br />
Your {2} between {3} and {4} was declined.<br />
<br />
Regards';
$lang['declineleavenotificationsubject'] = 'Your {1} request was declined';
$lang['filesharing_sharefoldermessage'] = 'I\'m sharing the following with you:<br />
{1}<br />
<br />
{2}';
$lang['filesharing_sharemessage'] = 'I\'m sharing the attached file with you. <br />
<br />
{1}';
$lang['filesharing_sharemessage_clicktoview'] = 'Click <a href=\'{1}\'>here</a> to view it.';
$lang['filesharing_sharesubject'] = '{1}';
$lang['grouppurchase_pricingmessage'] = 'A new price for {1} is now available. The prices of your affiliates are as follows: {2}  {3}';
$lang['grouppurchase_pricingsubject'] = 'A new price for {1} is available';
$lang['holidaysmessagebody'] = 'Following are year {1}\'s holidays: {2} N.B. Lunar holidays\' dates are subject to change.';
$lang['holidaysmessagesubject'] = 'Holidays of year {1}';
$lang['leaveapprovedmessage'] = 'Dear {1},<br />
<br />
Your {2} between {3} and {4} was approved.<br />
<br />
Regards';
$lang['leaveapprovedsubject'] = 'Your leave request was approved';
$lang['leavenotificationmessage'] = '{1} {6} a {2} between <strong>{3}</strong> and <strong>{4}</strong>{5}<br />
{7}{8}';
$lang['leavenotificationmessage_contactperson'] = 'You may contact {1} in case of urgent issues on {2}.';
$lang['leavenotificationmessage_days'] = ' - {1} working day(s).';
$lang['leavenotificationmessage_owncontact_email'] = '{1} will have access to e-mail, but can also be reached on: {2}';
$lang['leavenotificationmessage_owncontact_limitedemail'] = 'While away, {1} will have limited access to e-mail, but can be reached on: {2}';
$lang['leavenotificationsubject'] = '{1} {3} a {2} ({4}{5})';
$lang['leavenotificationsubject_taking'] = 'is taking';
$lang['leavenotificationsubject_took'] = 'took';
$lang['modifyleavemessage'] = '{1} modified their leave as follows:<br />
Type: {2}<br />
Start date: {3}<br />
End date: {4} {5} <br />
Reason: {6}<br />
<br />
<br />
<strong>Leaves Stats:</strong><br />
Can take {7} days during the given period out of its {8} basic entitlement. Additional {9} are provided.<br />
{10} days have been taken during the given period.<br />
Current basic balance*: <strong>{11}</strong> days. It will become <strong>{12}</strong> after approving this leave.<br />
<br />
To approve simply reply to this message, or click <a href=\'{13}\'>here</a>.<br />
<br />
<br />
<i>* basic balance does not include the additional (Extra) days</i>';
$lang['modifyleavenotificationmessage'] = '{1} is now taking a {2} between <strong>{3}</strong> and <strong>{4}</strong>{5}<br />
{6}';
$lang['modifyleavenotificationsubject'] = '{1} modified their leave {2}';
$lang['reportsready'] = 'Reports of Q{1} {2} - {3} are ready';
$lang['reportsreadymessage'] = 'All reports of {1} have been finalized.<br />
<br />
Please read the reports and then validate them in order to send them to the supplier.<br />
<br />
View all reports <a href=\'{2}\'>here</a>.';
$lang['requestleavemessage'] = '{1} requested a leave as follows:<br />
Type: {2}<br />
Start date: {3}<br />
End date: {4} {5} <br />
Reason: {6}<br />
<br />
<strong>Leaves Stats:</strong><br />
Can take {7} days during the given period out of its {8} basic entitlement. Additional {9} are provided.<br />
{10} days have been taken during the given period.<br />
Current basic balance*: <strong>{11}</strong> days. It will become <strong>{12}</strong> after approving this leave.<br />
<br />
To approve simply reply to this message, or click <a href=\'{13}\'>here</a>.<br />
<br />
<br />
<i>* basic balance does not include the additional (Extra) days</i>';
$lang['requestleavemessagesupervisor'] = '{1} requested a leave as follows:<br />
Type: {2}<br />
Start date: {3}<br />
End date: {4}<br />
Reason: {5}<br />
Approved by: {6}<br />
<br />
To approve simply reply to this message. or click <a href=\'{7}\'>here</a>.';
$lang['requestleavesubject'] = '{1} requested a {2} [{3}]';
$lang['resetemailmessage'] = 'Dear {1}<br />
<br />
Your password has been reset following your request<br />
<br />
Your new password is: {2}<br />
<br />
For any further assistance please contact the system administrator on {3}.';
$lang['revokeleavenotificationmessage'] = '{1} revoked the {2} between <strong>{3}</strong> and <strong>{4}</strong>.';
$lang['revokeleavenotificationmessageuser'] = 'Dear {1},<br />
<br />
Your {2} between {3} and {4} was revoked.<br />
<br />
Regards';
$lang['revokeleavenotificationsubject'] = '{1} revoked their {2}';
$lang['revokeleavenotificationsubjectuser'] = 'Your {1} was revoked';
$lang['sendbymaildefault'] = 'Dear all, <br />
<br />
Please find attached the {1} report for Orkila Distribution and Agency activities in the Middle East and African Markets. <br />
<br />
Please feel free to provide us with your comments, in order to improve this communication for our mutual business interests. <br />
<br />
Best regards, Orkila';
$lang['sendbymailsubject'] = 'ORKILA {1} Report - {2} - {3}';
$lang['surveys_invitation_message'] = 'Hello {1}<br />
<br />
You were invited to complete the following survey:<br /><br />
<strong>{2}</strong><br />
{3}<br />
<br />
To start filling, please click <a href=\'{4}\'>here</a>.<br />
<br />
Thank  you';
$lang['surveys_invitation_subject'] = 'New Survey: {1}';
$lang['survey_reminder_message'] = 'Dear {1},<br />
You have been invited to the follow survey(s), but you haven\'t responded yet:';
$lang['survey_reminder_subject'] = 'Fill Survey Reminder';
$lang['upcomingholidays_message'] = 'Following are the upcoming holidays of {1}:<br />
{2}';
$lang['upcomingholidays_subject'] = 'Your upcoming holidays';
$lang['visitreport_reminder_message'] = 'Dear {1},<br />
The Following visits have been carried but no visit report has been completed. Please complete the visit reports mentioned below:';
$lang['visitreport_reminder_subject'] = 'Visit Reports Reminder';
$lang['yournewpassword'] = 'Your New OCOS Account Password';
$lang['unmetchemicalsubject'] = 'You have unmet chemcial requests ';
$lang['unmetchemicalbody'] = 'The following chemical requests have not been completely responded to: ';
$lang['report_notviewdsubject'] = 'Not viewed reports Notifications';
$lang['report_notviewdmessage'] = 'The following QR have not been viewed by any of the recipients: ';
$lang['uncompletedcommunication'] = ' You Have Not completed Your communication With ';
$lang['uncompletedsubject'] = 'Uncompleted Sourcing Communication ';
?>