<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['adminreadyassist'] = 'The administrators are ready to assist you.';
$lang['callonnum'] = 'Call on {1}';
$lang['currqreportingstats'] = 'Current quarterly reporting stats';
$lang['duereports'] = 'Due quarterly reports';
$lang['edityourprofile'] = 'Edit your profile';
$lang['employeeslist'] = 'Employees list';
$lang['entitieslist'] = 'Directory';
$lang['fillvreport'] = 'Fill a visit report';
$lang['generateqreports'] = 'Generate quarterly reports';
$lang['intotal'] = 'in total';
$lang['lastfinalized'] = 'Last finalized reports';
$lang['leavesapproved'] = 'leave(s) were approved';
$lang['leavescurrentmonth'] = '{1} leave(s) during the current month for {2} day(s)';
$lang['leavestotal'] = 'leave(s) in total';
$lang['listqreports'] = 'List quarterly reports';
$lang['mainmessage'] = 'Welcome to Orkila Central Online System. Please find your way through this portal. You are able to prepare your quarterly, monthly, and visit reports, collaborate, request your leaves and more.';
$lang['submitsupportticket'] = 'Submit a support ticket';
$lang['submitticket'] = 'Submit Ticket';
$lang['submitticketexplain'] = 'Please fill the below information and click Submit Ticket. <br />
An IT support staff member will then take responsibility of your incident and follow up with you until the issue is resolved and the ticket is closed.';
$lang['successstories'] = 'Success Stories';
$lang['systemnews'] = 'OCOS news';
$lang['ticketdescription'] = 'Description';
$lang['ticketsubmitted'] = 'Support ticket was successfully submitted';
$lang['ticketsummary'] = 'Summary';
$lang['timecity'] = '{1} {2} time';
$lang['timecity2'] = '{1} {2} time';
$lang['timegmt'] = '{1} UTC time';
$lang['unfinalized'] = 'unfinalized';
$lang['usefulshortcuts'] = 'Userful shortcuts';
$lang['weheretohelp'] = ' We\'re here to help';
$lang['welcometoocos'] = 'Welcome to OCOS!';
$lang['worldtime'] = 'World \\\"time';
$lang['todayfxrates']='Today\'s FX Rates';
$lang['usdfxrates']='USD Exchnage Rates ';
?>