<?php

/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['adminreadyassist'] = 'The administrators are ready to assist you.';
$lang['edityourprofile'] = 'Edit your profile';
$lang['mainmessage'] = 'Welcome to Magister. Please find your way through this portal.';
$lang['submitsupportticket'] = 'Submit a support ticket';
$lang['submitticket'] = 'Submit Ticket';
$lang['submitticketexplain'] = 'Please fill the below information and click Submit Ticket. <br />
An IT support staff member will then take responsibility of your incident and follow up with you until the issue is resolved and the ticket is closed.';
$lang['systemnews'] = 'Magister news';
$lang['name'] = 'Name';
$lang['addcalendarevent'] = 'Add Calendar Event';
$lang['daterange'] = 'Date Range';
?>