<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['businessinfo'] = 'Business Information';
$lang['businessregions'] = 'Business Regions';
$lang['chemicalsubstance'] = 'Chemical Substance';
$lang['commercial'] = 'Commercial';
$lang['companyname'] = 'Company Name';
$lang['contactdetails'] = 'Contact Details';
$lang['contactperson'] = 'Contact Persons';
$lang['coordinators'] = 'Coordinators';
$lang['customers'] = 'Customers';
$lang['editrepresentative'] = 'Edit representative';
$lang['employees'] = 'Employees';
$lang['facetoface'] = 'Face To Face';
$lang['fax'] = 'Fax';
$lang['finmanager'] = 'Finance Manager';
$lang['fulladdress'] = 'Full address';
$lang['fullname'] = 'Full name';
$lang['gm'] = 'General Manager';
$lang['hrinfo'] = 'HR Information';
$lang['hrmanager'] = 'HR Manager';
$lang['infomail'] = 'Info mail';
$lang['internalextensions'] = 'Internal Extensions';
$lang['lastfiles'] = 'Last Files';
$lang['lastfinalized'] = 'Last finalized reports';
$lang['lastvisited'] = 'Last visited reports';
$lang['management'] = 'Management';
$lang['name'] = 'Name';
$lang['pobox'] = 'P.O. Box';
$lang['position'] = 'Position';
$lang['productquality'] = 'Product Quality';
$lang['receivesqr'] = 'Receives Quarterly Reports';
$lang['representativeslist'] = 'List of representatives';
$lang['rmlevel'] = 'Relation Maturity Level (RML)';
$lang['schedule'] = 'Schedule';
$lang['segment'] = 'Segment';
$lang['segments'] = 'Segments';
$lang['servicequality'] = 'Service Quality';
$lang['supervisor'] = 'Supervisor';
$lang['suppliers'] = 'Suppliers';
$lang['telephone'] = 'Telephone';
$lang['telephonecall'] = 'Telephone Call';
$lang['territory'] = 'Territory';
$lang['workshift'] = 'Work Shift';
?>