<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['businessinfo'] = 'Business Information';
$lang['businessregions'] = 'Business Regions';
$lang['companyname'] = 'Company Name';
$lang['contactdetails'] = 'Contact Details';
$lang['contactperson'] = 'Contact Persons';
$lang['customers'] = 'Customers';
$lang['editrepresentative'] = 'Edit representative';
$lang['employees'] = 'Employees';
$lang['facetoface'] = 'Face To Face';
$lang['fax'] = 'Fax';
$lang['fulladdress'] = 'Address';
$lang['fullname'] = 'Full name';
$lang['gm'] = 'General Manager';
$lang['hrinfo'] = 'HR Information';
$lang['hrmanager'] = 'Hr Manager';
$lang['infomail'] = 'Info mail';
$lang['internalextensions'] = 'Internal Extensions';
$lang['lastfiles'] = 'Last Files';
$lang['lastfinalized'] = 'Last finalized reports';
$lang['lastvisited'] = 'Last visited reports';
$lang['management'] = 'Management';
$lang['createbrand']='Create Brand';
$lang['name'] = 'Name';
$lang['pobox'] = 'P.O. Box';
$lang['position'] = 'Position';
$lang['representativeslist'] = 'List of representatives';
$lang['rmlevel'] = 'Relation Maturity Level (RML)';
$lang['segment'] = 'Segment';
$lang['segments'] = 'Segments';
$lang['supervisor'] = 'Supervisor';
$lang['suppliers'] = 'Suppliers';
$lang['telephone'] = 'Telephone';
$lang['telephonecall'] = 'Telephone Call';
$lang['territory'] = 'Territory';
$lang['workshift'] = 'Work Shift';
$lang['item'] = 'Item';
$lang['addasegment'] = "Add a Segment";
$lang['listavailablesegments'] = "List of Available Segments";
$lang['nosegementsavailable'] = "No segments are yet available";
$lang['segmentadded'] = "Segment was added successfully";
$lang['segmentadderror'] = "An error occured while adding the segment";
$lang['pleasefillintitle'] = "Please fill-in a title for the segment";
$lang['coordinator'] = "Coordinators";
$lang['employees'] = "Employees";
$lang['segmentprofile'] = "Segment Profile";
$lang['productypes'] = "Product Types";
$lang['competitorprod'] = "Competitor Producer";
$lang['cif'] = " CIF";
$lang['competitortrader']='Competitor Trader';
$lang['customers'] = "Customers";
$lang['segmentalreadyexists'] = "A segment with the same name already exists";
?>