<?php

/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['accountsettings'] = 'Account Settings';
$lang['change'] = 'Change';
$lang['changepassword'] = 'Change Password';
$lang['confirmpassword'] = 'Confirm Password';
$lang['displayname'] = 'Display Name';
$lang['editprofileinformation'] = 'Manage your account';
$lang['firstname'] = 'First Name';
$lang['fulladdress'] = 'Full address';
$lang['fullname'] = 'Full name';
$lang['lastname'] = 'Last Name';
$lang['lastvisited'] = 'Last visited on';
$lang['manageyouraccount'] = 'Manage your account';
$lang['modify'] = 'Modify';
$lang['passwordalreadyused'] = 'You have specified a password that you have already used before. Please specify another.';
$lang['passwordhasexpired'] = 'Your password has expired; please choose a new one.';
$lang['passwordnomatch'] = 'The new passwords did not match';
$lang['passwordsuccessfullychanged'] = 'Your password was successfully changed';
$lang['profilesuccessfullyupdated'] = 'Your profile was successfully updated';
$lang['pwdpatternnomatch'] = 'The password you specified does not match the required pattern.';
$lang['signaturefooter'] = 'Please consider the environment before printing this e-mail.';
$lang['unfinalized'] = 'unfinalized';
$lang['uploadinginprogress'] = 'Uploading in progress...';
$lang['viewyourprofile'] = 'View your Profile';
$lang['wrongid'] = 'Wrong user ID';
$lang['wrongoldpassword'] = 'Wrong Old Password';
$lang['oldpassword'] = 'Old Password';
$lang['newpassword'] = 'New Password';
?>