<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['accountsettings'] = 'Account Settings';
$lang['address'] = 'Address';
$lang['assistant'] = 'Assistant';
$lang['bbpin'] = 'BB Pin';
$lang['buildingname'] = 'Building';
$lang['change'] = 'Change';
$lang['changepassword'] = 'Change Password';
$lang['changeprofilepic'] = 'Change Profile Picture';
$lang['city'] = 'City';
$lang['confirmpassword'] = 'Confirm Password';
$lang['contactinformation'] = 'Contact Information';
$lang['currqreportingstats'] = 'Current quarterly reporting stats';
$lang['defaultlanguage'] = 'Default language';
$lang['defaultmodule'] = 'Default module';
$lang['employeeslistmosaiicview'] = 'employeeslistmosaiicview';
$lang['displayname'] = 'Display Name';
$lang['downloadsignature'] = 'Download Signature';
$lang['duereports'] = 'Due quarterly reports';
$lang['editprofileinformation'] = 'Manage your account';
$lang['emailsignature'] = 'Email Signature';
$lang['employeeinformation'] = 'Employee Information';
$lang['employeeslistmosaiicview'] = 'Employees List Mosaiic View';
$lang['employeeslist'] = 'Employees list';
$lang['errorupdatingprofile'] = 'An error occured while updating profile';
$lang['filter'] = 'Filter';
$lang['firstname'] = 'First Name';
$lang['fulladdress'] = 'Full address';
$lang['fullname'] = 'Full name';
$lang['generatesignature'] = 'Generate Email Signature';
$lang['imagesignature'] = 'Image Signature';
$lang['internalextension'] = 'Internal extension';
$lang['intotal'] = 'in total';
$lang['jobdescription'] = 'Job description';
$lang['lastfinalized'] = 'Last finalized reports';
$lang['lastleaves'] = 'Last {1} leaves';
$lang['lastlogs'] = 'last {1} logs';
$lang['lastname'] = 'Last Name';
$lang['lastvisited'] = 'Last visited on';
$lang['mainaffiliate'] = 'Main affiliate';
$lang['manageyouraccount'] = 'Manage your account';
$lang['middlename'] = 'Middle Name';
$lang['mobile'] = 'Mobile';
$lang['mobileisprivate_tip'] = 'If ticked, your mobile number will not appear in your profile and signature.';
$lang['modify'] = 'Modify';
$lang['newfilenotification'] = 'Send me notification of new shared files';
$lang['newpassword'] = 'New Password';
$lang['oldpassword'] = 'Old Password';
$lang['onlyfiletypesallowed'] = 'Only png, jpg, and gif files are allowed';
$lang['passwordalreadyused'] = 'You have specified a password that you have already used before. Please specify another.';
$lang['passwordhasexpired'] = 'Your password has expired; please choose a new one.';
$lang['passwordnomatch'] = 'The new passwords did not match';
$lang['passwordpattern_tooltip'] = '<ul><br />
<li>minimum of 8 characters</li><br />
<li>at least 1 number</li><br />
<li>at least 1 uppercase character</li><br />
<li>at least 1 lowercase character</li><br />
<li>at least 1 symbol</li><br />
</ul>';
$lang['passwordsuccessfullychanged'] = 'The password was successfully changed';
$lang['plaintextsignature'] = 'Plain Text Signature';
$lang['pobox'] = 'P.O. Box';
$lang['position'] = 'Position';
$lang['postcode'] = 'Post code';
$lang['private'] = 'Private';
$lang['profilesuccessfullyupdated'] = 'Your profile was successfully updated';
$lang['pwdpatternnomatch'] = 'The password you specified does not match the required pattern.';
$lang['reportsto'] = 'Reports to';
$lang['segments'] = 'Segments';
$lang['selectprofilepicture'] = 'Select a profile picture';
$lang['signaturefooter'] = 'Please consider the environment before printing this e-mail.';
$lang['signaturefooter_2'] = 'This e-mail is confidential and intended only for the addressee(s) shown. If you are not an intended recipient, please be advised that any use, dissemination, forwarding or copying of this e-mail is strictly prohibited. Internet e-mails are not necessarily secure and the Orkila group does not accept responsibility for changes made to this message after it was sent. Should you receive this transmission in error, notify the sender immediately. Thank you.';
$lang['signatureguideline'] = 'To add the signature to your MS Outlook, please follow the below steps:<br />
<br />
1. Go to %AppData%\\Microsoft\\Signatures through your Windows Explorer.<br />
<br />
2. Copy/Paste all file in this archive there.<br />
<br />
3. In MS Outlook, go to Tools > Options > Mail Format > Signatures.<br />
<br />
4. If not already selected, select \'Orkila\' under Choose Default Signature.';
$lang['skype'] = 'Skype';
$lang['telephone'] = 'Telephone';
$lang['unfinalized'] = 'unfinalized';
$lang['uploadinginprogress'] = 'Uploading in progress...';
$lang['viewyourprofile'] = 'View your Profile';
$lang['workswith'] = 'Works With';
$lang['wrongid'] = 'Wrong user ID';
$lang['downloadcontact'] = 'Download Contact';
$lang['downloademployeescards'] = 'Download All Employees Contacts';

$lang['birthdayisprivate'] = 'Make my birthday private';
$lang['birthdayisprivate_tip'] = 'If ticked, your birthday will remain private, else a notification will be send to your affiliate emloyees on your birthday';
?>