<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['businessinfo'] = 'Business Information';
$lang['contributor'] = 'contributor';
$lang['businessinfo'] = 'Business Information';
$lang['businessregions'] = 'Business Regions';
$lang['companyname'] = 'Company Name';
$lang['segname'] = 'Name';
$lang['contactdetails'] = 'Contact Details';
$lang['contactperson'] = 'Contact Persons';
$lang['customers'] = 'Customers';
$lang['editrepresentative'] = 'Edit representative';
$lang['employees'] = 'Employees';
$lang['facetoface'] = 'Face To Face';
$lang['fax'] = 'Fax';
$lang['fulladdress'] = 'Address';
$lang['fullname'] = 'Full name';
$lang['gm'] = 'General Manager';
$lang['hrinfo'] = 'HR Information';
$lang['hrmanager'] = 'Hr Manager';
$lang['infomail'] = 'Info mail';
$lang['internalextensions'] = 'Internal Extensions';
$lang['lastfiles'] = 'Last Files';
$lang['lastfinalized'] = 'Last finalized reports';
$lang['lastvisited'] = 'Last visited reports';
$lang['management'] = 'Management';
$lang['name'] = 'Name';
$lang['pobox'] = 'P.O. Box';
$lang['position'] = 'Position';
$lang['representativeslist'] = 'List of representatives';
$lang['rmlevel'] = 'Relation Maturity Level (RML)';
$lang['segment'] = 'Segment';
$lang['segments'] = 'Segments';
$lang['supervisor'] = 'Supervisor';
$lang['suppliers'] = 'Suppliers';
$lang['telephone'] = 'Telephone';
$lang['telephonecall'] = 'Telephone Call';
$lang['territory'] = 'Territory';
$lang['workshift'] = 'Work Shift';

$lang['brand'] = 'Brand';
$lang['addmarketdata'] = 'Add Market Data';
$lang['endproduct'] = 'End Product Type';

$lang['annualpotential'] = 'Annual Potential';
$lang['item'] = 'Item';
$lang['competitortrader'] = 'Competitor Trader';
$lang['competitorprod'] = 'Competitor Producer';
$lang['marketshareperc'] = 'Market Share %';
$lang['marketshareqty'] = 'Market Share Qty';
$lang['price'] = 'Unit Price';
$lang['usd'] = 'USD/KG';
$lang['competition'] = 'Competition Information';
$lang['comment'] = 'Comments';
$lang['competitor'] = 'Competitors';
$lang['addmarketdata'] = 'Add Market Data';
$lang['viewmrktbox'] = 'View Market Box';
$lang['detailmktintelbox'] = 'Detailed Market Intelligence Box';
$lang['competitorsuppliers'] = 'Competitor Suppliers';
$lang['competitorproducts'] = 'Products';
$lang['competitortradersuppliers'] = 'Competitor trader';
$lang['competitorprodsuppliers'] = 'Competitor producer';
$lang['addasegment'] = "Add a Segment";
$lang['listavailablesegments'] = "List of Available Segments";
$lang['segmentlist'] = 'Segments List';
$lang['nosegementsavailable'] = "No segments are yet available";
$lang['segmentadded'] = "Segment was added successfully";
$lang['segmentadderror'] = "An error occured while adding the segment";
$lang['pleasefillintitle'] = "Please fill-in a title for the segment";
$lang['coordinator'] = "Coordinators";
$lang['isexclusive'] = "Is Exclusive";
$lang['selectiveproducts'] = "Selective Products";
$lang['employees'] = "Employees";
$lang['segmentprofile'] = "Segment Profile";
$lang['productypes'] = "Product Types";
$lang['customers'] = "Customers";
$lang['competitortype'] = "Competitor Type";
$lang['competitorname'] = "Competitor Name";
$lang['coveredcountries'] = "Search Covered Contries";
$lang['contractualinformation'] = "Contractual Information";
$lang['segmentalreadyexists'] = "A segment with the same name already exists";
?>