<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['addnewcustomer'] = 'Add a New Customer';
$lang['addnewproduct'] = 'Add a New Product';
$lang['begincaps'] = 'BEGIN';
$lang['cancel'] = 'Cancel';
$lang['code'] = 'Code';
$lang['companyname'] = 'Company name';
$lang['country'] = 'Country';
$lang['entityalreadyexists'] = 'An entity with the same name already exists';
$lang['entitycreated'] = 'Entity was successfully created';
$lang['erroraddingproduct'] = 'An error occurred while adding the product';
$lang['errorcreatingentity'] = 'Error creating entity';
$lang['errorcreatingreprentative'] = 'Error creating representative';
$lang['excludekeycustomers'] = 'Exclude key customers';
$lang['excludeproductsactivity'] = 'Exclude products activity';
$lang['exclude_tip'] = 'If ticked, you will be able to finalize the report without having to fill data in this stage.';
$lang['fillatleastonecustomerrow'] = 'Fill at least one customer';
$lang['fillatleastoneproductrow'] = 'Fill at least one product row';
$lang['fillonemktreportsection'] = 'Fill at least one section of the market report';
$lang['finishedmypart'] = 'I have finished my part';
$lang['generic'] = 'Generic';
$lang['invalidentityemail'] = 'An invalid entity email was provided';
$lang['isdone_tip'] = 'If ticked, you will be marked as done and will not get reminders anymore. If you are the last person to fill this report, and you save rather than finalize, the system will automatically finalize the report.';
$lang['joinedsuccessfully'] = 'Joined Successfully';
$lang['keycustomer'] = 'Key Customer';
$lang['marketreport_exclude_tip'] = 'If ticked, there is no need to fill this segment market report and it will not be included in the final report.';
$lang['name'] = 'Name';
$lang['noproductsavailable'] = 'No products are yet available';
$lang['noreportsavailable'] = 'No reports are available';
$lang['notcontractedsupp'] = 'This is a supplier with whom we don\'t have an agreement. There is no need to mention customers names, unless there is a specific reason for that.';
$lang['productadded'] = 'Product {1} was added successfully';
$lang['productalreadyexists'] = 'A product with the same name already exists';
$lang['representativecreated'] = 'The representative was successfully created';
$lang['representativeexists'] = 'A representative with the same name already exists';
$lang['representativename'] = 'Representative name';
$lang['savedsuccessfully'] = 'Saved Successfully';
$lang['saveerror'] = 'An error occured while saving data';
$lang['selectareport'] = 'Select a Report';
$lang['specifyanaffiliate'] = 'Please specify an affiliate';
$lang['specifycompanyname'] = 'Please specify a company name';
$lang['specifyrepemail'] = 'Specify representative email';
$lang['transfill_tip'] = 'If ticked, you will not be recorded as contributor in the report.';
$lang['transparentlyfill'] = 'Transparently fill report';
$lang['unspecifiedsegment'] = 'Unspecified Segment';
$lang['wrongforecastsexist'] = 'Wrong year end forecasts were provided; they should be at least as the following:';
$lang['wrongforecastgoback'] = 'Wrong year end forecasts were provided; please go back and correct them.';
$lang['fillreport'] = 'Fill Report';
?>