<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['accesssurveylink'] = 'To access the survey, please click the following: {1}';
$lang['anonymousfilling'] = 'Anonymous filling';
$lang['category'] = 'Category';
$lang['choices'] = 'Choices';
$lang['closingdate'] = 'Auto-close on';
$lang['closingdate_tip'] = 'After this date, invitees will not be able to respond anymore.';
$lang['country'] = 'Country';
$lang['createsurvey'] = 'Create Survey';
$lang['createtemplate'] = 'Create Survey Template';
$lang['description'] = 'Description';
$lang['emailonly'] = 'Valid email address only';
$lang['fillsurvey'] = 'Fill Survey';
$lang['invitationgroup'] = 'Invitation Group';
$lang['invitations'] = 'Invitations';
$lang['questiondesc'] = 'Question Description';
$lang['invitee'] = 'Invitee';
$lang['inviteesnumber_tip'] = 'Specified number will be used to randomly select x number of invitees out of the checked.';
$lang['listsurveys'] = 'List Surveys';
$lang['maxchars'] = 'Max of {1} characters';
$lang['minchars'] = 'Min of {1} characters';
$lang['mustinviteusers'] = 'Survey is not public, you must invite at least one user';
$lang['noresponses'] = 'No responses yet';
$lang['numbersonly'] = 'Numbers only';
$lang['other'] = 'Other';
$lang['position'] = 'Position';
$lang['publicfill'] = 'Public Fill';
$lang['publicfill_note'] = 'If survey is not public, you must invite users';
$lang['publicresult'] = 'Public Result';
$lang['questionaverage'] = 'Avg.';
$lang['randomizeinvitations'] = 'Randomize Invitations';
$lang['reference'] = 'Reference';
$lang['respondant'] = 'Respondant';
$lang['responses'] = 'Responses';
$lang['responsetime'] = 'Response Time';
$lang['segment'] = 'Segment';
$lang['subject'] = 'Subject';
$lang['survey'] = 'Survey';
$lang['surveydate'] = 'Date';
$lang['surveyexists'] = 'A survey with the same subject exists';
$lang['surveyexpired'] = 'Survey has expired';
$lang['surveysassociations'] = 'Associates with';
$lang['surveysinvitation'] = 'Invitations';
$lang['template'] = 'Template';
$lang['violation'] = 'One or more inputs you made violate the requirements';
?>