<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['choices'] = 'Choices';
$lang['choicesseperator'] = 'Choices Separator';
$lang['choices_tip'] = 'You can add multiple choices each on new line. To assign value for the choice, separate it with semi-column (;), ex: choice1;value1';
$lang['commentsfieldtitle'] = 'Comments Field Title';
$lang['commentsfieldtitle_tip'] = 'Title for the comments field';
$lang['duplicationquestionname'] = 'Two or more questions in this template use the same name';
$lang['duplicationsectionname'] = 'Two or more sections in this template use the same name';
$lang['fieldsize'] = 'Field Size';
$lang['forceanonymousfilling'] = 'Force Anonymous Filling';
$lang['incorrechoices'] = 'You have to  assign value for the choice<br />
At least one of your questions has wrong choices setting';
$lang['isrequired'] = 'Required';
$lang['publicallyavailable'] = 'Publically Available';
$lang['question'] = 'Question';
$lang['questiondesc'] = 'Question Description';
$lang['questiontype'] = 'Question Type';
$lang['section'] = 'Section';
$lang['sectiondesciption'] = 'Section Description';
$lang['sectiontitle'] = 'Section Title';
$lang['sequence'] = 'Sequence';
$lang['surveytemplateexists'] = 'A template with the same name already exsits';
$lang['surveytemplatetitle'] = 'Title';
$lang['validationcriterion'] = 'Validation Criterion';
$lang['validationtype'] = 'Validation Type';
$lang['createbasedonanother'] = 'Create based on another template';
$lang['loadquestins'] = 'Load questions';
$lang['sectiontemplatealreadyused'] = 'Section Template Already Used';
$lang['commentsfieldrownumber'] = 'Comments Field Row Number';
$lang['commentsfieldsize_tip'] = 'The Number Of Rows That Will Determine The Size Of The Comments Field';
?>