<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['choices'] = 'Choices';
$lang['choices_tip'] = 'You can add multiple choices each on new line. To use assign value for the choice, separate it with semi-column \";\", ex: choice1;value1';
$lang['commentsfieldsize'] = 'Comments Field Size';
$lang['commentsfieldsize_tip'] = 'Character number of the comments field';
$lang['commentsfieldtitle'] = 'Comments Field Title';
$lang['commentsfieldtitle_tip'] = 'Title for the comments field';
$lang['duplicationquestionname'] = 'Two or more questions in this template use the same name';
$lang['duplicationsectionname'] = 'Two or more sections in this template use the same name';
$lang['fieldsize'] = 'Field Size';
$lang['forceanonymousfilling'] = 'Force Anonymous Filling';
$lang['isrequired'] = 'Required';
$lang['question'] = 'Question';
$lang['questiondesc'] = 'Question Description';
$lang['questiontype'] = 'Question Type';
$lang['section'] = 'Section';
$lang['sectiontitle'] = 'Section Title';
$lang['sequence'] = 'Sequence';
$lang['surveytemplateexists'] = 'A template with the same name already exsits';
$lang['surveytemplatetitle'] = 'Title';
$lang['validationcriterion'] = 'Validation Criterion';
$lang['validationtype'] = 'Validation Type';
?>