<?php
/* * *******************************\
  DO NOT EDIT THIS FILE
  PLEASE USE the Admin CP
  \******************************** */

$lang['accesssurveylink'] = 'To access the survey, please click the following: {1}';
$lang['anonymousfilling'] = 'Anonymous filling';
$lang['basictemplateinfo'] = 'Basic Template Information';
$lang['category'] = 'Category';
$lang['choice'] = 'Choice';
$lang['choices'] = 'Choices';
$lang['closingdate'] = 'Auto-close on';
$lang['closingdate_tip'] = 'After this date, invitees will not be able to respond anymore.';
$lang['collectexternalresponses'] = 'External Responses';
$lang['country'] = 'Country';
$lang['createsurvey'] = 'Create Survey';
$lang['createtemplate'] = 'Create Survey Template';
$lang['custominvitationbody_note'] = 'Use {link} anywhere in body to display the survey link in the message';
$lang['customizeinvitation'] = 'Customize Invitation Message';
$lang['customizeinvitationmessage'] = 'Customize Invitation Message';
$lang['description'] = 'Description';
$lang['emailonly'] = 'Valid email address only';
$lang['errorsaving'] = 'Error saving';
$lang['externalinvitations'] = 'External Invitations';
$lang['fillallrequiredfields'] = 'Please fill all required fields';
$lang['fillsurvey'] = 'Fill Survey';
$lang['internalinvitations'] = 'Internal Invitations';
$lang['invitationbody'] = 'Body';
$lang['invitationgroup'] = 'Invitation Group';
$lang['invitations'] = 'Invitations';
$lang['invitationsubject'] = 'Subject';
$lang['invitee'] = 'Invitee';
$lang['inviteesnumber_tip'] = 'Specified number will be used to randomly select x number of invitees out of the checked.';
$lang['isanswer'] = 'Is Answer';
$lang['listsurveys'] = 'List Surveys';
$lang['maxchars'] = 'Max of {1} characters';
$lang['minchars'] = 'Min of {1} characters';
$lang['modifysurvey'] = 'Modify Survey';
$lang['mustinviteusers'] = 'Survey is not public, you must invite at least one user';
$lang['noresponses'] = 'No responses yet';
$lang['numbersonly'] = 'Numbers only';
$lang['other'] = 'Other';
$lang['pendingresponses'] = 'Pending Responses';
$lang['position'] = 'Position';
$lang['previewtemplate'] = 'Preview Template';
$lang['publicfill'] = 'Public Fill';
$lang['publicfill_note'] = 'If survey is not public, you must invite users';
$lang['publicresult'] = 'Public Result';
$lang['questionaverage'] = 'Avg.';
$lang['quiz'] = 'Quiz';
$lang['randomizeinvitations'] = 'Randomize Invitations';
$lang['reference'] = 'Reference';
$lang['remindersent'] = 'Reminders have been sent';
$lang['respondant'] = 'Respondant';
$lang['responses'] = 'Responses';
$lang['responsetime'] = 'Response Time';
$lang['segment'] = 'Segment';
$lang['send'] = 'Send';
$lang['sendreminders'] = 'Send Reminders';
$lang['subject'] = 'Subject';
$lang['survey'] = 'Survey';
$lang['surveydate'] = 'Date';
$lang['surveyexists'] = 'A survey with the same subject exists';
$lang['surveyexpired'] = 'Survey has expired';
$lang['surveyquestions'] = 'Survey Questions';
$lang['surveysassociations'] = 'Associates with';
$lang['surveysinvitation'] = 'Invitations';
$lang['surveys_reminder_message'] = 'Dear {1},<br />
<br />
You have been invited to the following survey(s), but you have not responded yet:';
$lang['survey_reminder_message'] = 'Dear {1},<br />
<br />
You have been invited to the survey: {2}, but you have not responded yet.<br />
<br />
To access the survey, please click the following: {3}';
$lang['survey_reminder_subject'] = 'Survey(s) Reminder';
$lang['template'] = 'Template';
$lang['value'] = 'Value';
$lang['violation'] = 'One or more inputs you made violate the requirements';
$lang['result'] = 'Result';
$lang['totalscore'] = 'Total Score';
$lang['failed'] = 'Failed';
$lang['passed'] = 'Passed';
?>