<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$settings['present2'] = "present2";
$settings['test2'] = "test2";
$settings['test2'] = "test2";

?>