<?php
/*********************************\ 
  DO NOT EDIT THIS FILE
 PLEASE USE the Admin CP
\*********************************/

$lang['alreadyexists'] = "A file with the same name already exists.";
$lang['erroruploading'] = "An error occured while uploading.";
$lang['iwas'] = "I Was";
$lang['sizetoobig'] = "The file size is too big.";
$lang['typenotallowed'] = "The type of file you are tyring to upload is not allowed.";
$lang['uploaded'] = "The file was uploaded successfully.";

?>