<thead>
    <tr>
        <th>{$lang->companyname}</th>
        <th>{$lang->companytype}</th>
        <th>{$lang->country}</th>
        <th>{$lang->representatives}</th>
        <th>{$lang->email}</th>
        <th>{$lang->addressLine1}</th>
        <th>{$lang->phone1}</th>
        <th>{$lang->phone2}</th>
        <th>{$lang->fax1}</th>
        <th>{$lang->fax2}</th>
        <th>{$lang->mainEmail}</th>
        <th>{$lang->website}</th>
    </tr>
</thead>