<html>
    <head>
        <title>{$core->settings[systemtitle]} | {$lang->potentialmarketdata}</title>
        {$headerinc}
        <script src="{$core->settings[rootdir]}/js/profiles_marketintelligence.min.js" type="text/javascript"></script>
    </head>
    <body>
        {$header}
    <tr>
        {$menu}
        <td class="contentContainer" colspan="2">
            <h1>{$lang->potentialmarketdata}</h1>
            <div style="float: right">{$addmarketdata_link}</div>
            <table class="datatable_basic table table-bordered row-border hover order-column" data-totalcolumns="14,15,16" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>{$lang->affiliate}</th>
                        <th>{$lang->customer}</th>
                        <th>{$lang->country}</th>
                        <th>{$lang->product}</th>
                        <th>{$lang->supplier}</th>
                        <th>{$lang->chemicalsubs}</th>
                        <th>{$lang->basicingredients}</th>
                        <th>{$lang->functionalproperty}</th>
                        <th>{$lang->application}</th>
                        <th>{$lang->segment}</th>
                        <th>{$lang->brand}</th>
                        <th>{$lang->brandendproduct}</th>
                        <th>{$lang->endproducttype}</th>
                        <th>{$lang->characteristic}</th>
                        <th>{$lang->potentialqty}</th>
                        <th>{$lang->marketshare}</th>
                        <th>{$lang->price}</th>
                        <th>{$lang->date}</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>{$lang->affiliate}</th>
                        <th>{$lang->customer}</th>
                        <th>{$lang->country}</th>
                        <th>{$lang->product}</th>
                        <th>{$lang->supplier}</th>
                        <th>{$lang->chemicalsubs}</th>
                        <th>{$lang->basicingredients}</th>
                        <th>{$lang->functionalproperty}</th>
                        <th>{$lang->application}</th>
                        <th>{$lang->segment}</th>
                        <th>{$lang->brand}</th>
                        <th>{$lang->brandendproduct}</th>
                        <th>{$lang->endproducttype}</th>
                        <th>{$lang->characteristic}</th>
                        <th>{$lang->potentialqty}</th>
                        <th>{$lang->marketshare}</th>
                        <th>{$lang->price}</th>
                        <th>{$lang->date}</th>
                        <th>&nbsp;</th>
                    </tr>
                </tfoot>
                <tbody>
                    {$marketpotdata_list}
                </tbody>
            </table>
            <div style="width:40%; float:left; margin-top:0px;" class="smalltext"><form method='post' action='$_SERVER[REQUEST_URI]'>{$lang->perlist}: <input type='text' size='4' id='perpage_field' name='perpage' value='{$core->settings[itemsperlist]}' class="smalltext"/></form></div>
        </td>
    </tr>
    {$footer}
    {$popup_createbrand}
    {$popup_marketdata}
</body>
</html>