<tr>
    <td>{$checkbox}</td>
    <td>{$job_applicant['displayname']}</td>
    <td>{$job_applicant['email']}</td>
    <td>{$job_applicant['phone']}</td>
    <td>{$job_applicant['submissiondate']}</td>
    <td>{$vacancy['displayname']}</td>
    <td>{$vacancy['affiliate']}</td>
    <td></td>
</tr>