<tr id='{$product_rowid}' class="{$altrow_class}">
    <td><span id='product_name_{$product_rowid}'></span> <input type="hidden" value="{$stockorder_data[pid][$key]}" name="products[{$product_rowid}][pid]" id="pid_{$product_rowid}"/></td>
    <td><select id="packingType_{$product_rowid}_output" name="products[{$product_rowid}][packingType]" >{$packingtype}</select><div name="packingType_{$product_rowid}_Loading" id="packingType_{$product_rowid}_Loading"></div></td>
    <td><input type="text" name="products[{$product_rowid}][packingWeight]" id="packingWeight_{$product_rowid}" accept="numeric" size="5" autocomplete='off' value="{$stockorder_data[packingWeight][$key]}"/><div name="packingWeight_{$product_rowid}_Loading" id="packingWeight_{$product_rowid}_Loading"></div></td> 
    <td><input type="text" name="products[{$product_rowid}][quantity]" id="quantity_{$product_rowid}" accept="numeric" size="5" autocomplete='off' value="{$stockorder_data[quantity][$key]}" /></td> 
    <td><input type="text" name="products[{$product_rowid}][purchasePrice]" id="purchasePrice_{$product_rowid}" accept="numeric" size="5" autocomplete='off' value="{$stockorder_data[purchasePrice]}"/></td>
    <td><input type="text" name="products[{$product_rowid}][sellingPrice]" id="sellingPrice_{$product_rowid}" accept="numeric" size="5" autocomplete='off' value="{$stockorder_data[sellingPrice][$key]}"/></td>
    <td><input type="text" name="products[{$product_rowid}][clearingFees]" id="clearingFees[{$product_rowid}]"accept="numeric" size="5" autocomplete='off' value="{$stockorder_data[clearingFees][$key]}"/></td> 
    <td><input type="text" name="products[{$product_rowid}][lcFees]" id="lcFees[{$product_rowid}]" accept="numeric" size="5" autocomplete='off' value="{$stockorder_data[lcFees][$key]}"/></td> 
    <td><span id="purchaseAmount_{$product_rowid}_output">0</span><input type="hidden" name="products[{$product_rowid}][purchaseAmount]" id="purchaseAmount_{$product_rowid}" accept="numeric" size="5" autocomplete='off' value="{$stockorder_data[purchaseAmount][$key]}"/></td>
    <td><span id="sellingAmount_{$product_rowid}_output">0</span><input type="hidden" name="products[{$product_rowid}][sellingAmount]" id="sellingAmount_{$product_rowid}" accept="numeric" size="5" autocomplete='off' value="{$stockorder_data[sellingAmount][$key]}"/></td>
</tr>