<tr>
    <td>{$product[name]}</td>
    <td>{$product[packingType]}</td>
    <td>{$product[packingWeight]}</td>
    <td>{$product[quantity]}</td>
    <td>{$product[clearingFees]}</td>
    <td>{$product[lcFees]}</td>
    <td>{$product[purchasePrice]}</td>
    <td>{$product[purchaseAmount]}</td>
    <td>{$product[costPrice]}</td>
    <td>{$product[sellingPrice]}</td>
    <td>{$product[grossMargin]}</td>
    <td>{$product[netMargin]}</td>
    <td>{$product[netMarginPerc]}</td>
    <td>{$product[estsaledate_output]}</td>
</tr>